### PR TITLE
Public Holidays for Malaysia added up to end of 2019

### PR DESCRIPTION
**Pull request by Meridien**

### CODE REVIEW

**Comment by philss** [comment]
@Meridien thank you for the PR! Can you check [the main issue](https://github.com/magnetis/spok/issues/28) again? There is one item missing:

> 5. Add the calendar name to the Spok::Workday::CALENDARS constant here.

**Comment by Meridien** [comment]
My bad @philss I have added that in too now. Cheers!

**Comment by philss** [comment]
@Meridien no problem 👍 

One more thing: can you fix the indentation in the `lib/spok/workday.rb` (I think it's using tabs instead of spaces)?

Also, could you squash the three commits into one?

**Comment by Meridien** [comment]
Hi @philss thanks for your patience here, I have corrected the indentation in workday.rb and have squashed to 1 commit. Cheers!

**Comment by philss** [comment]
@Meridien no worries. Thank you! 😃

**Pull request merged**
